# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mohammed/CLionProjects/Opdracht1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mohammed/CLionProjects/Opdracht1/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mohammed/CLionProjects/Opdracht1/build/CMakeFiles /home/mohammed/CLionProjects/Opdracht1/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mohammed/CLionProjects/Opdracht1/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Opdracht1

# Build rule for target.
Opdracht1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Opdracht1
.PHONY : Opdracht1

# fast build rule for target.
Opdracht1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/build
.PHONY : Opdracht1/fast

Color.o: Color.cpp.o
.PHONY : Color.o

# target to build an object file
Color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/Color.cpp.o
.PHONY : Color.cpp.o

Color.i: Color.cpp.i
.PHONY : Color.i

# target to preprocess a source file
Color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/Color.cpp.i
.PHONY : Color.cpp.i

Color.s: Color.cpp.s
.PHONY : Color.s

# target to generate assembly for a file
Color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/Color.cpp.s
.PHONY : Color.cpp.s

Line2D.o: Line2D.cpp.o
.PHONY : Line2D.o

# target to build an object file
Line2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/Line2D.cpp.o
.PHONY : Line2D.cpp.o

Line2D.i: Line2D.cpp.i
.PHONY : Line2D.i

# target to preprocess a source file
Line2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/Line2D.cpp.i
.PHONY : Line2D.cpp.i

Line2D.s: Line2D.cpp.s
.PHONY : Line2D.s

# target to generate assembly for a file
Line2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/Line2D.cpp.s
.PHONY : Line2D.cpp.s

Point2D.o: Point2D.cpp.o
.PHONY : Point2D.o

# target to build an object file
Point2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/Point2D.cpp.o
.PHONY : Point2D.cpp.o

Point2D.i: Point2D.cpp.i
.PHONY : Point2D.i

# target to preprocess a source file
Point2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/Point2D.cpp.i
.PHONY : Point2D.cpp.i

Point2D.s: Point2D.cpp.s
.PHONY : Point2D.s

# target to generate assembly for a file
Point2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/Point2D.cpp.s
.PHONY : Point2D.cpp.s

ZBuffer.o: ZBuffer.cpp.o
.PHONY : ZBuffer.o

# target to build an object file
ZBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/ZBuffer.cpp.o
.PHONY : ZBuffer.cpp.o

ZBuffer.i: ZBuffer.cpp.i
.PHONY : ZBuffer.i

# target to preprocess a source file
ZBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/ZBuffer.cpp.i
.PHONY : ZBuffer.cpp.i

ZBuffer.s: ZBuffer.cpp.s
.PHONY : ZBuffer.s

# target to generate assembly for a file
ZBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/ZBuffer.cpp.s
.PHONY : ZBuffer.cpp.s

engine.o: engine.cc.o
.PHONY : engine.o

# target to build an object file
engine.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/engine.cc.o
.PHONY : engine.cc.o

engine.i: engine.cc.i
.PHONY : engine.i

# target to preprocess a source file
engine.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/engine.cc.i
.PHONY : engine.cc.i

engine.s: engine.cc.s
.PHONY : engine.s

# target to generate assembly for a file
engine.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/engine.cc.s
.PHONY : engine.cc.s

l_parser.o: l_parser.cc.o
.PHONY : l_parser.o

# target to build an object file
l_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/l_parser.cc.o
.PHONY : l_parser.cc.o

l_parser.i: l_parser.cc.i
.PHONY : l_parser.i

# target to preprocess a source file
l_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/l_parser.cc.i
.PHONY : l_parser.cc.i

l_parser.s: l_parser.cc.s
.PHONY : l_parser.s

# target to generate assembly for a file
l_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/l_parser.cc.s
.PHONY : l_parser.cc.s

utils/easy_image.o: utils/easy_image.cc.o
.PHONY : utils/easy_image.o

# target to build an object file
utils/easy_image.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/utils/easy_image.cc.o
.PHONY : utils/easy_image.cc.o

utils/easy_image.i: utils/easy_image.cc.i
.PHONY : utils/easy_image.i

# target to preprocess a source file
utils/easy_image.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/utils/easy_image.cc.i
.PHONY : utils/easy_image.cc.i

utils/easy_image.s: utils/easy_image.cc.s
.PHONY : utils/easy_image.s

# target to generate assembly for a file
utils/easy_image.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/utils/easy_image.cc.s
.PHONY : utils/easy_image.cc.s

utils/ini_configuration.o: utils/ini_configuration.cc.o
.PHONY : utils/ini_configuration.o

# target to build an object file
utils/ini_configuration.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/utils/ini_configuration.cc.o
.PHONY : utils/ini_configuration.cc.o

utils/ini_configuration.i: utils/ini_configuration.cc.i
.PHONY : utils/ini_configuration.i

# target to preprocess a source file
utils/ini_configuration.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/utils/ini_configuration.cc.i
.PHONY : utils/ini_configuration.cc.i

utils/ini_configuration.s: utils/ini_configuration.cc.s
.PHONY : utils/ini_configuration.s

# target to generate assembly for a file
utils/ini_configuration.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/utils/ini_configuration.cc.s
.PHONY : utils/ini_configuration.cc.s

vector/vector3d.o: vector/vector3d.cc.o
.PHONY : vector/vector3d.o

# target to build an object file
vector/vector3d.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/vector/vector3d.cc.o
.PHONY : vector/vector3d.cc.o

vector/vector3d.i: vector/vector3d.cc.i
.PHONY : vector/vector3d.i

# target to preprocess a source file
vector/vector3d.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/vector/vector3d.cc.i
.PHONY : vector/vector3d.cc.i

vector/vector3d.s: vector/vector3d.cc.s
.PHONY : vector/vector3d.s

# target to generate assembly for a file
vector/vector3d.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Opdracht1.dir/build.make CMakeFiles/Opdracht1.dir/vector/vector3d.cc.s
.PHONY : vector/vector3d.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Opdracht1"
	@echo "... Color.o"
	@echo "... Color.i"
	@echo "... Color.s"
	@echo "... Line2D.o"
	@echo "... Line2D.i"
	@echo "... Line2D.s"
	@echo "... Point2D.o"
	@echo "... Point2D.i"
	@echo "... Point2D.s"
	@echo "... ZBuffer.o"
	@echo "... ZBuffer.i"
	@echo "... ZBuffer.s"
	@echo "... engine.o"
	@echo "... engine.i"
	@echo "... engine.s"
	@echo "... l_parser.o"
	@echo "... l_parser.i"
	@echo "... l_parser.s"
	@echo "... utils/easy_image.o"
	@echo "... utils/easy_image.i"
	@echo "... utils/easy_image.s"
	@echo "... utils/ini_configuration.o"
	@echo "... utils/ini_configuration.i"
	@echo "... utils/ini_configuration.s"
	@echo "... vector/vector3d.o"
	@echo "... vector/vector3d.i"
	@echo "... vector/vector3d.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

